---
version: "3.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
      - AUTO_UPDATE=true
    volumes:
      - /home/pi/jackett-config:/config
      - /media/usb/transmission:/downloads
    restart: unless-stopped
    network_mode: "service:openvpn-client"
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.pi.local`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  autoheal:
    container_name: autoheal
    build: ./autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /home/pi/lib:/config
      - /home/pi/media:/media
      - /media/usb/transmission/movies:/movies
      - /media/usb/transmission/tv:/tv
    restart: unless-stopped 
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    domainname: pi.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8053:80/tcp"
    environment:
      - TZ="America/Chicago"
      - WEBPASSWORD=/run/secrets/web_pass
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=pihole.pi.local
      - PROXY_LOCATION=pihole
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    secrets:
      - web_pass
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.pi.local`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
  openvpn-client:
    build: ./openvpn-client
    cap_add:
      - NET_ADMIN
    container_name: openvpn_running
    ports:
      - "9091:9091"
      - "7878:7878"
      - "8989:8989"
      - "9117:9117"
    environment:
      - LOCAL_NETWORKS=192.168.0.0/24
    volumes:
      - pia_port:/var/run/pia
      - /home/pi/torrent_config:/config
    devices:
      - /dev/net/tun
    restart: unless-stopped 
  transmission-client:
    container_name: transmission_run
    build: ./transmission-client
    network_mode: "service:openvpn-client"
    depends_on:
      - openvpn-client
    volumes:
      - pia_port:/var/run/pia
      - /media/usb:/data
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/torrent_config:/config
    restart: unless-stopped 
  radarr:
    image: linuxserver/radarr
    network_mode: "service:openvpn-client"
    container_name: radarr
    labels: 
      - "autoheal=true"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
      - UMASK_SET=022
    volumes:
      - /home/pi/radarr:/config
      - /media/usb/transmission/movies:/movies
      - /media/usb/:/data
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    network_mode: "service:openvpn-client"
    container_name: sonarr
    labels: 
      - "autoheal=true"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
      - UMASK_SET=022
    volumes:
      - /home/pi/sonarr:/config
      - /media/usb/transmission/tv:/tv
      - /media/usb/:/data
    restart: unless-stopped
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /home/pi/heimdall-config:/config
    ports:
      - "8082:80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`dashboard.pi.local`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
secrets:
  web_pass:
    file: web_pwd.txt
volumes:
  pia_port:
  portainer_data:

